import Head from "next/head";
import Splash from "../components/layouts/Splash";
import React, { useState, useEffect } from "react";
import { useRouter } from "next/router";
import Loading from "../components/Loading";
export default function Home() {
  const router = useRouter();
  const [showSplash, setShowSplash] = useState(true);
  const [showLoading, setShowLoading] = useState(false);

  useEffect(() => {
    // 일정 시간(예: 5초) 후에 Splash 화면을 숨깁니다.
    const timeout = setTimeout(() => {
      // 3초 후 "/main" 페이지로 자동으로 이동합니다.
      setShowSplash(false);
      setShowLoading(true);
      setTimeout(() => {
        router.push("/main");
      }, 2000);
    }, 2000);

    // 컴포넌트가 언마운트될 때 clearTimeout을 호출하여 타이머를 정리합니다.
    return () => clearTimeout(timeout);
  }, []);

  return (
    <>
      <Head>
        <title>LOVESG</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {showSplash && <Splash />}
        {showLoading && <Loading />}
        {/* 이 부분에 메인 컨텐츠를 추가할 수 있습니다. */}
      </div>
    </>
  );
}
